#ifndef _BOARD_CONDIG_H
#define _BOARD_CONDIG_H

#ifdef ALIENTEK_MINI
#define BEEP_GPIO_PERIPH RCC_APB2Periph_GPIOA
#define BEEP_GPIO_GROUP GPIOA
#define BEEP_GPIO_PIN GPIO_Pin_14

#define LED1_GPIO_PERIPH RCC_APB2Periph_GPIOD
#define LED1_GPIO_GROUP GPIOD
#define LED1_GPIO_PIN GPIO_Pin_2
#define LED0_GPIO_PERIPH RCC_APB2Periph_GPIOA
#define LED0_GPIO_GROUP GPIOA
#define LED0_GPIO_PIN GPIO_Pin_8

#else//default

#define BEEP_GPIO_PERIPH RCC_APB2Periph_GPIOB
#define BEEP_GPIO_GROUP GPIOB
#define BEEP_GPIO_PIN GPIO_Pin_5

#define LED1_GPIO_PERIPH RCC_APB2Periph_GPIOA
#define LED1_GPIO_GROUP GPIOA
#define LED1_GPIO_PIN GPIO_Pin_14
#define LED0_GPIO_PERIPH RCC_APB2Periph_GPIOA
#define LED0_GPIO_GROUP GPIOA
#define LED0_GPIO_PIN GPIO_Pin_15
#endif

#endif
